# Generated by Django 5.1.5 on 2025-05-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_user_email'),
    ]

    operations = [
    ]
