# Generated by Django 5.1.5 on 2025-05-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20250514_2133'),
    ]

    operations = [
    ]
