# Generated by Django 5.1.5 on 2025-05-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_fix_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
